connection hisense
address 192.168.1.103:36669

username hisenseservice
password multimqttservice

clientid HomeAssistant

start_type automatic
try_private true
cleansession true

bridge_tls_version tlsv1.2
bridge_cafile /mosquitto/certs/hisense_ca1.crt
bridge_certfile /mosquitto/certs/rcm_certchain_pem.cer
bridge_keyfile /mosquitto/certs/rcm_pem_privkey.pkcs8
bridge_insecure true

topic /remoteapp/# both 0 hisense ""
